# Generated by Django 5.2.5 on 2025-11-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formregistration',
            name='email',
        ),
    ]
