# Generated by Django 5.2.5 on 2025-11-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_remove_formregistration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, choices=[('SSITE', 'SSITE'), ('UASAO', 'UASAO'), ('MCSA', 'MCSA')], max_length=255, null=True),
        ),
    ]
