# Generated by Django 5.2.5 on 2025-11-25 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_organization_remove_user_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formregistration',
            old_name='organization',
            new_name='OrganizationName',
        ),
    ]
