# Generated by Django 5.2.5 on 2025-11-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='OrganizationName',
            field=models.CharField(blank=True, choices=[('SSITE', 'SSITE'), ('UASAO', 'UASAO'), ('MCSA', 'MCSA'), ('JPIA', 'JPIA'), ('LTSP', 'LTSP'), ('BHS-PHS', 'BHS-PHS'), ('NSC', 'NSC'), ('JPPhA', 'JPPhA'), ('CRCYC', 'CRCYC'), ('CDW', 'CDW'), ('BATAS', 'BATAS'), ('CREATE', 'CREATE'), ('PICE', 'PICE'), ('AAA', 'AAA'), ('PIIE', 'PIIE'), ('BACC', 'BACC'), ('PSYCHSOC', 'PSYCHSOC'), ('LEAD', 'LEAD'), ('CHARMS', 'CHARMS'), ('ICpEP.se', 'ICpEP.se'), ('INA', 'INA'), ('UACSC', 'UACSC')], max_length=255, null=True, unique=True),
        ),
    ]
