# Generated by Django 5.2.5 on 2025-11-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_alter_organization_organizationname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formregistration',
            old_name='OrganizationName',
            new_name='organization',
        ),
    ]
